### ISSUE TITLE
Merge features?

### ISSUE THREAD

**Issue by jonathantneal** [seaneking/postcss-position#6]
In May, I wrote my first PostCSS plugin, short. It shorthanded a bunch of properties, including position. Today I revisited short and started breaking it (which was really a plugin pack) into smaller packages like https://github.com/jonathantneal/postcss-position.

Then I saw we’ve got practically the same thing going on! So, I’d love to team up, merge the asterisk feature into your plugin, and then use this plugin in the next **short** plugin pack.

Before I make a pull though, does this interest you at all? I can keep them separate (and add a `short` prefix to mine) if you really think we’re doing different enough things.

**Comment by madeleineostoja** [comment]
I'd like to keep this plugin as close to spec as possible (ie: same logic as margin/padding shorthands only), if only because this is a part of [Rucksack](https://github.com/simplaio/rucksack) and we're trying to keep feature bloat to an absolute minimum. Especially since you can achieve the same thing as the asterisk with the proper property (`auto`). Sorry. But feel free to fork this and merge it as a new repo :-)
