### ISSUE TITLE
calc in value

### ISSUE THREAD

**Issue by fogrew** [seaneking/postcss-position#7]
I can't write `position: absolute 0 auto 0 calc(100% + 1px);`

**Comment by madeleineostoja** [comment]
This is because the plugin currently finds values in the `position` declaration by splitting at every space, which `calc(100% + 1px)` obviously breaks. Other than regex madness can't think off the top of my head how to resolve. I'll have a think and make a patch soon. If you want to get around it now just remove the spaces in your calc statement.
